# Generated by Django 5.0.6 on 2024-07-18 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('unit', models.IntegerField()),
                ('description', models.TextField(max_length=3000)),
                ('hospital', models.CharField(max_length=300)),
                ('needed_date_time', models.DateTimeField()),
                ('requested', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DonorModel',
            fields=[
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, primary_key=True, serialize=False)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('phone_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=128)),
                ('status', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PatientModel',
            fields=[
                ('email', models.EmailField(max_length=200, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True, max_length=300, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('illness', models.TextField(max_length=400)),
                ('password', models.CharField(max_length=128)),
                ('status', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Blood_accept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Donor_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('accepted', models.BooleanField(default=False)),
                ('unit', models.IntegerField()),
                ('needed_unit', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('blood_request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.bloodrequest')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.donormodel')),
            ],
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.patientmodel'),
        ),
    ]
